// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Executor struct {
	ID           int64
	RevisionID   int64
	ExecutorName string
	AnchorName   string
	ContainerID  string
	ImgName      string
}

type Revision struct {
	ID          int64
	PackageName string
	Version     string
	DeployTime  time.Time
}
