// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Deployment struct {
	ID         int64
	PkgName    string
	DeployedAt time.Time
}

type Executor struct {
	ID           int64
	DeploymentID int64
	ExecutorName string
	ContainerID  string
}
