// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createExecutor = `-- name: CreateExecutor :one

INSERT INTO executors (revision_id, executor_name, anchor_name, container_id, img_name)
VALUES (?, ?, ?, ?, ?)
RETURNING id, revision_id, executor_name, anchor_name, container_id, img_name
`

type CreateExecutorParams struct {
	RevisionID   int64
	ExecutorName string
	AnchorName   string
	ContainerID  string
	ImgName      string
}

// Executors CRUD
func (q *Queries) CreateExecutor(ctx context.Context, arg CreateExecutorParams) (Executor, error) {
	row := q.db.QueryRowContext(ctx, createExecutor,
		arg.RevisionID,
		arg.ExecutorName,
		arg.AnchorName,
		arg.ContainerID,
		arg.ImgName,
	)
	var i Executor
	err := row.Scan(
		&i.ID,
		&i.RevisionID,
		&i.ExecutorName,
		&i.AnchorName,
		&i.ContainerID,
		&i.ImgName,
	)
	return i, err
}

const createRevision = `-- name: CreateRevision :one

INSERT INTO revisions (package_name, version, deploy_time)
VALUES (?, ?, ?)
RETURNING id, package_name, version, deploy_time
`

type CreateRevisionParams struct {
	PackageName string
	Version     string
	DeployTime  time.Time
}

// Revisions CRUD
func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) (Revision, error) {
	row := q.db.QueryRowContext(ctx, createRevision, arg.PackageName, arg.Version, arg.DeployTime)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.PackageName,
		&i.Version,
		&i.DeployTime,
	)
	return i, err
}

const deleteExecutor = `-- name: DeleteExecutor :exec
DELETE FROM executors
WHERE id = ?
`

func (q *Queries) DeleteExecutor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExecutor, id)
	return err
}

const deleteRevision = `-- name: DeleteRevision :exec
DELETE FROM revisions
WHERE id = ?
`

func (q *Queries) DeleteRevision(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRevision, id)
	return err
}

const getExecutor = `-- name: GetExecutor :one
SELECT id, revision_id, executor_name, anchor_name, container_id, img_name
FROM executors
WHERE id = ?
`

func (q *Queries) GetExecutor(ctx context.Context, id int64) (Executor, error) {
	row := q.db.QueryRowContext(ctx, getExecutor, id)
	var i Executor
	err := row.Scan(
		&i.ID,
		&i.RevisionID,
		&i.ExecutorName,
		&i.AnchorName,
		&i.ContainerID,
		&i.ImgName,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT id, package_name, version, deploy_time
FROM revisions
WHERE id = ?
`

func (q *Queries) GetRevision(ctx context.Context, id int64) (Revision, error) {
	row := q.db.QueryRowContext(ctx, getRevision, id)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.PackageName,
		&i.Version,
		&i.DeployTime,
	)
	return i, err
}

const getRevisionByPackageAndVersion = `-- name: GetRevisionByPackageAndVersion :one
SELECT id, package_name, version, deploy_time
FROM revisions
WHERE package_name = ? AND version = ?
`

type GetRevisionByPackageAndVersionParams struct {
	PackageName string
	Version     string
}

func (q *Queries) GetRevisionByPackageAndVersion(ctx context.Context, arg GetRevisionByPackageAndVersionParams) (Revision, error) {
	row := q.db.QueryRowContext(ctx, getRevisionByPackageAndVersion, arg.PackageName, arg.Version)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.PackageName,
		&i.Version,
		&i.DeployTime,
	)
	return i, err
}

const getRevisionWithExecutors = `-- name: GetRevisionWithExecutors :many

SELECT
    r.id, r.package_name, r.version, r.deploy_time,
    e.id, e.revision_id, e.executor_name, e.anchor_name, e.container_id, e.img_name
FROM revisions r
LEFT JOIN executors e ON e.revision_id = r.id
WHERE r.id = ?
ORDER BY e.id
`

type GetRevisionWithExecutorsRow struct {
	Revision Revision
	Executor Executor
}

// Revision with executors
func (q *Queries) GetRevisionWithExecutors(ctx context.Context, id int64) ([]GetRevisionWithExecutorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRevisionWithExecutors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevisionWithExecutorsRow
	for rows.Next() {
		var i GetRevisionWithExecutorsRow
		if err := rows.Scan(
			&i.Revision.ID,
			&i.Revision.PackageName,
			&i.Revision.Version,
			&i.Revision.DeployTime,
			&i.Executor.ID,
			&i.Executor.RevisionID,
			&i.Executor.ExecutorName,
			&i.Executor.AnchorName,
			&i.Executor.ContainerID,
			&i.Executor.ImgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevisionWithExecutorsByPackageAndVersion = `-- name: GetRevisionWithExecutorsByPackageAndVersion :many
SELECT
    r.id, r.package_name, r.version, r.deploy_time,
    e.id, e.revision_id, e.executor_name, e.anchor_name, e.container_id, e.img_name
FROM revisions r
LEFT JOIN executors e ON e.revision_id = r.id
WHERE r.package_name = ? AND r.version = ?
ORDER BY e.id
`

type GetRevisionWithExecutorsByPackageAndVersionParams struct {
	PackageName string
	Version     string
}

type GetRevisionWithExecutorsByPackageAndVersionRow struct {
	Revision Revision
	Executor Executor
}

func (q *Queries) GetRevisionWithExecutorsByPackageAndVersion(ctx context.Context, arg GetRevisionWithExecutorsByPackageAndVersionParams) ([]GetRevisionWithExecutorsByPackageAndVersionRow, error) {
	rows, err := q.db.QueryContext(ctx, getRevisionWithExecutorsByPackageAndVersion, arg.PackageName, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevisionWithExecutorsByPackageAndVersionRow
	for rows.Next() {
		var i GetRevisionWithExecutorsByPackageAndVersionRow
		if err := rows.Scan(
			&i.Revision.ID,
			&i.Revision.PackageName,
			&i.Revision.Version,
			&i.Revision.DeployTime,
			&i.Executor.ID,
			&i.Executor.RevisionID,
			&i.Executor.ExecutorName,
			&i.Executor.AnchorName,
			&i.Executor.ContainerID,
			&i.Executor.ImgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutorsByRevision = `-- name: ListExecutorsByRevision :many
SELECT id, revision_id, executor_name, anchor_name, container_id, img_name
FROM executors
WHERE revision_id = ?
ORDER BY id
`

func (q *Queries) ListExecutorsByRevision(ctx context.Context, revisionID int64) ([]Executor, error) {
	rows, err := q.db.QueryContext(ctx, listExecutorsByRevision, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Executor
	for rows.Next() {
		var i Executor
		if err := rows.Scan(
			&i.ID,
			&i.RevisionID,
			&i.ExecutorName,
			&i.AnchorName,
			&i.ContainerID,
			&i.ImgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT id, package_name, version, deploy_time
FROM revisions
ORDER BY deploy_time DESC
`

func (q *Queries) ListRevisions(ctx context.Context) ([]Revision, error) {
	rows, err := q.db.QueryContext(ctx, listRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Revision
	for rows.Next() {
		var i Revision
		if err := rows.Scan(
			&i.ID,
			&i.PackageName,
			&i.Version,
			&i.DeployTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecutor = `-- name: UpdateExecutor :one
UPDATE executors
SET executor_name = ?, anchor_name = ?, container_id = ?, img_name = ?
WHERE id = ?
RETURNING id, revision_id, executor_name, anchor_name, container_id, img_name
`

type UpdateExecutorParams struct {
	ExecutorName string
	AnchorName   string
	ContainerID  string
	ImgName      string
	ID           int64
}

func (q *Queries) UpdateExecutor(ctx context.Context, arg UpdateExecutorParams) (Executor, error) {
	row := q.db.QueryRowContext(ctx, updateExecutor,
		arg.ExecutorName,
		arg.AnchorName,
		arg.ContainerID,
		arg.ImgName,
		arg.ID,
	)
	var i Executor
	err := row.Scan(
		&i.ID,
		&i.RevisionID,
		&i.ExecutorName,
		&i.AnchorName,
		&i.ContainerID,
		&i.ImgName,
	)
	return i, err
}

const updateRevision = `-- name: UpdateRevision :one
UPDATE revisions
SET package_name = ?, version = ?, deploy_time = ?
WHERE id = ?
RETURNING id, package_name, version, deploy_time
`

type UpdateRevisionParams struct {
	PackageName string
	Version     string
	DeployTime  time.Time
	ID          int64
}

func (q *Queries) UpdateRevision(ctx context.Context, arg UpdateRevisionParams) (Revision, error) {
	row := q.db.QueryRowContext(ctx, updateRevision,
		arg.PackageName,
		arg.Version,
		arg.DeployTime,
		arg.ID,
	)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.PackageName,
		&i.Version,
		&i.DeployTime,
	)
	return i, err
}
