// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createDeployment = `-- name: CreateDeployment :one

INSERT INTO deployments (pkg_name, deployed_at)
VALUES (?, ?)
RETURNING id, pkg_name, deployed_at
`

type CreateDeploymentParams struct {
	PkgName    string
	DeployedAt time.Time
}

// Deployments CRUD
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment, arg.PkgName, arg.DeployedAt)
	var i Deployment
	err := row.Scan(&i.ID, &i.PkgName, &i.DeployedAt)
	return i, err
}

const createExecutor = `-- name: CreateExecutor :one

INSERT INTO executors (deployment_id, executor_name, container_id)
VALUES (?, ?, ?)
RETURNING id, deployment_id, executor_name, container_id
`

type CreateExecutorParams struct {
	DeploymentID int64
	ExecutorName string
	ContainerID  string
}

// Executors CRUD
func (q *Queries) CreateExecutor(ctx context.Context, arg CreateExecutorParams) (Executor, error) {
	row := q.db.QueryRowContext(ctx, createExecutor, arg.DeploymentID, arg.ExecutorName, arg.ContainerID)
	var i Executor
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ExecutorName,
		&i.ContainerID,
	)
	return i, err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments
WHERE id = ?
`

func (q *Queries) DeleteDeployment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeployment, id)
	return err
}

const deleteExecutor = `-- name: DeleteExecutor :exec
DELETE FROM executors
WHERE id = ?
`

func (q *Queries) DeleteExecutor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExecutor, id)
	return err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, pkg_name, deployed_at
FROM deployments
WHERE id = ?
`

func (q *Queries) GetDeployment(ctx context.Context, id int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(&i.ID, &i.PkgName, &i.DeployedAt)
	return i, err
}

const getDeploymentWithExecutors = `-- name: GetDeploymentWithExecutors :many

SELECT
    d.id          AS deployment_id,
    d.pkg_name    AS deployment_pkg_name,
    d.deployed_at AS deployment_deployed_at,
    e.id          AS executor_id,
    e.deployment_id,
    e.executor_name,
    e.container_id
FROM deployments d
LEFT JOIN executors e ON e.deployment_id = d.id
WHERE d.id = ?
ORDER BY e.id
`

type GetDeploymentWithExecutorsRow struct {
	DeploymentID         int64
	DeploymentPkgName    string
	DeploymentDeployedAt time.Time
	ExecutorID           sql.NullInt64
	DeploymentID_2       sql.NullInt64
	ExecutorName         sql.NullString
	ContainerID          sql.NullString
}

// Deployment with executors (join)
func (q *Queries) GetDeploymentWithExecutors(ctx context.Context, id int64) ([]GetDeploymentWithExecutorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentWithExecutors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeploymentWithExecutorsRow
	for rows.Next() {
		var i GetDeploymentWithExecutorsRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.DeploymentPkgName,
			&i.DeploymentDeployedAt,
			&i.ExecutorID,
			&i.DeploymentID_2,
			&i.ExecutorName,
			&i.ContainerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutor = `-- name: GetExecutor :one
SELECT id, deployment_id, executor_name, container_id
FROM executors
WHERE id = ?
`

func (q *Queries) GetExecutor(ctx context.Context, id int64) (Executor, error) {
	row := q.db.QueryRowContext(ctx, getExecutor, id)
	var i Executor
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ExecutorName,
		&i.ContainerID,
	)
	return i, err
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, pkg_name, deployed_at
FROM deployments
ORDER BY deployed_at DESC
`

func (q *Queries) ListDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(&i.ID, &i.PkgName, &i.DeployedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutorsByDeployment = `-- name: ListExecutorsByDeployment :many
SELECT id, deployment_id, executor_name, container_id
FROM executors
WHERE deployment_id = ?
ORDER BY id
`

func (q *Queries) ListExecutorsByDeployment(ctx context.Context, deploymentID int64) ([]Executor, error) {
	rows, err := q.db.QueryContext(ctx, listExecutorsByDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Executor
	for rows.Next() {
		var i Executor
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.ExecutorName,
			&i.ContainerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeployment = `-- name: UpdateDeployment :one
UPDATE deployments
SET pkg_name = ?, deployed_at = ?
WHERE id = ?
RETURNING id, pkg_name, deployed_at
`

type UpdateDeploymentParams struct {
	PkgName    string
	DeployedAt time.Time
	ID         int64
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, updateDeployment, arg.PkgName, arg.DeployedAt, arg.ID)
	var i Deployment
	err := row.Scan(&i.ID, &i.PkgName, &i.DeployedAt)
	return i, err
}

const updateExecutor = `-- name: UpdateExecutor :one
UPDATE executors
SET executor_name = ?, container_id = ?
WHERE id = ?
RETURNING id, deployment_id, executor_name, container_id
`

type UpdateExecutorParams struct {
	ExecutorName string
	ContainerID  string
	ID           int64
}

func (q *Queries) UpdateExecutor(ctx context.Context, arg UpdateExecutorParams) (Executor, error) {
	row := q.db.QueryRowContext(ctx, updateExecutor, arg.ExecutorName, arg.ContainerID, arg.ID)
	var i Executor
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ExecutorName,
		&i.ContainerID,
	)
	return i, err
}
